


// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `MainConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=.;Database=ProjectManager;User Id=sa;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
// <auto-generated />

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

namespace ProjectManager.Entity
{
}
#pragma warning restore 1591
